#!/usr/bin/env bash
# modules/02-mergerfs-snapraid/schedule.sh — SnapRAID scheduling via systemd timers or cron
# Depends on: lib/{logging,idempotency}.sh

NAS_SETUP_DIR="$(dirname "$(dirname "$(dirname "${BASH_SOURCE[0]}")")")"
TEMPLATE_DIR="${NAS_SETUP_DIR}/templates"
SYSTEMD_DIR="/etc/systemd/system"
SCRIPTS_DIR="/var/lib/nas-setup/scripts"

# The "safe sync" script checks the diff threshold before syncing
_create_safe_sync_script() {
    mkdir -p "$SCRIPTS_DIR"
    cat > "${SCRIPTS_DIR}/snapraid-sync-safe.sh" << EOF
#!/bin/bash
# SnapRAID safe sync — generated by nas-setup
# Aborts sync if too many files changed (protects against accidental mass-delete)
THRESHOLD=${SNAPRAID_DIFF_THRESHOLD:-20}
LOG_TAG="snapraid-sync"

DIFF_OUT=\$(snapraid diff 2>&1)
DELETED=\$(echo "\$DIFF_OUT" | grep -oP '\d+(?= removed)' | head -1)
DELETED=\${DELETED:-0}
TOTAL=\$(echo "\$DIFF_OUT" | grep -oP '\d+(?= equal)' | head -1)
TOTAL=\${TOTAL:-1}

if [ "\$TOTAL" -gt 0 ]; then
    PCT=\$(( (DELETED * 100) / TOTAL ))
    if [ "\$PCT" -gt "\$THRESHOLD" ]; then
        logger -t "\$LOG_TAG" "ABORTADO: \${PCT}% de archivos eliminados (umbral: \${THRESHOLD}%). Revisa manualmente."
        echo "SYNC ABORTADO: \${PCT}% eliminados supera umbral del \${THRESHOLD}%"
        exit 1
    fi
fi

logger -t "\$LOG_TAG" "Iniciando sync (\${DELETED} eliminados, \${TOTAL} total)"
snapraid sync
EXIT_CODE=\$?
logger -t "\$LOG_TAG" "Sync completado con código: \$EXIT_CODE"
exit \$EXIT_CODE
EOF
    chmod +x "${SCRIPTS_DIR}/snapraid-sync-safe.sh"
    log_success "Script de sync seguro creado: ${SCRIPTS_DIR}/snapraid-sync-safe.sh"
}

_install_systemd_units() {
    local units=(
        "snapraid-sync.service"
        "snapraid-sync.timer"
        "snapraid-scrub.service"
        "snapraid-scrub.timer"
        "snapraid-smart.service"
        "snapraid-smart.timer"
    )

    for unit in "${units[@]}"; do
        local template="${TEMPLATE_DIR}/${unit}.j2"
        local dest="${SYSTEMD_DIR}/${unit}"

        if [[ ! -f "$template" ]]; then
            log_warn "Template no encontrado: $template"
            continue
        fi

        envsubst < "$template" > "$dest"
        log_debug "Unit instalada: $dest"
    done

    systemctl daemon-reload
    log_success "Unidades systemd instaladas"
}

_install_cron() {
    log_info "Configurando cron para SnapRAID..."
    local cron_file="/etc/cron.d/snapraid"

    cat > "$cron_file" << EOF
# SnapRAID schedule — generated by nas-setup
# Sync diario a las ${SNAPRAID_SYNC_HOUR}:00
0 ${SNAPRAID_SYNC_HOUR} * * * root ${SCRIPTS_DIR}/snapraid-sync-safe.sh >> /var/log/snapraid-sync.log 2>&1

# Scrub semanal el ${SNAPRAID_SCRUB_DAY} a las 4:00
0 4 * * ${SNAPRAID_SCRUB_DAY} root /usr/bin/snapraid scrub -p ${SNAPRAID_SCRUB_PERCENT} -o 0 >> /var/log/snapraid-scrub.log 2>&1

# SMART mensual el día 1 a las 5:00
0 5 1 * * root /usr/bin/snapraid smart >> /var/log/snapraid-smart.log 2>&1
EOF
    log_success "Cron configurado en: $cron_file"
}

_enable_systemd_timers() {
    local timers=("snapraid-sync.timer" "snapraid-scrub.timer" "snapraid-smart.timer")

    for timer in "${timers[@]}"; do
        systemctl enable "$timer" >> "$LOG_FILE" 2>&1
        systemctl start "$timer" >> "$LOG_FILE" 2>&1
        log_success "Timer habilitado: $timer"
    done

    echo ""
    log_info "Próximas ejecuciones programadas:"
    systemctl list-timers snapraid-*.timer --no-pager 2>/dev/null | while read -r line; do
        echo -e "  ${DIM}${line}${RESET}"
    done
}

configure_schedule() {
    skip_if_done "snapraid_schedule" "configuración de schedule SnapRAID" && return 0

    log_info "Creando script de sync seguro..."
    _create_safe_sync_script

    local schedule_type="${SCHEDULE_TYPE:-systemd}"

    if [[ "$schedule_type" == "cron" ]]; then
        _install_cron
    else
        log_info "Instalando unidades systemd..."
        _install_systemd_units
        log_info "Habilitando timers..."
        _enable_systemd_timers
    fi

    state_mark "snapraid_schedule"
    log_success "Schedule configurado (${schedule_type})"
    echo ""
    echo -e "  ${CYAN}Sync diario   : ${BOLD}${SNAPRAID_SYNC_HOUR}:00${RESET}"
    echo -e "  ${CYAN}Scrub semanal : ${BOLD}${SNAPRAID_SCRUB_DAY} 04:00 (${SNAPRAID_SCRUB_PERCENT}%)${RESET}"
    echo -e "  ${CYAN}SMART mensual : ${BOLD}día 1 de cada mes 05:00${RESET}"
    echo -e "  ${CYAN}Umbral diff   : ${BOLD}${SNAPRAID_DIFF_THRESHOLD}% (aborta sync si más archivos eliminados)${RESET}"
    echo ""
}
